# Generated by Django 5.2.11 on 2026-02-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayplan',
            options={},
        ),
        migrations.AddField(
            model_name='dayplan',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='plan_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
