# Generated by Django 5.2.11 on 2026-02-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_dayplan_options_dayplan_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayplan',
            options={'ordering': ['day_number']},
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='plan_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
